FORMAT: 1A
HOST: https://mobile.foreupsoftware.com/api_rest/index.php/

# foreUp API
        
The foreUp API can be used to access sales data, tee time usage, and other information from courses you have permission to access.  

The responses follow the JSONapi spec, read about it here: http://jsonapi.org/.

They have several imeplementations for parsing responses here: http://jsonapi.org/implementations/.

# Group Secured Access


## Authentication [/tokens]


### Create a New Token [POST]

To authenticate with the api you must first create a JWT using your username/password.  To learn more about JWT go here: https://jwt.io/.

+ Request (application/json)

            {
            "email": "testaccount@test.com",
            "password": "testaccount@test.com"
            }

+ Response 200 (application/json)

    + Body

            {
              "data": {
                "type": "token",
                "id": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0NzQ5MjI5MzgsImV4cCI6MTQ3NzUxNDkzOCwibGV2ZWwiOjAsImNpZCI6MCwiZW1wbG95ZWUiOmZhbHNlLCJ1aWQiOjY0ODI3Mjh9.go-Bf_6X8qByMu9JblewsmQt1dsqOu_70z6IlYYaZgGbsvjf9uQI0-RFSEivALntv0HF6-6WN9T5FxLpGyxcNA",
                "attributes": []
              }
            }
# Group Courses 
    
## Courses [/courses]

This endpoint will list all the courses which you have access too.

### List All[GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "courses",
                  "id": "6270",
                  "attributes": {
                    "title": "Cascade Golf Course",
                    "street": "The place",
                    "city": "Cityville",
                    "state": "UT",
                    "zip": "84097",
                    "phone": "5555555555",
                    "app_store_description": "",
                    "app_short_title": "",
                    "test_flight_email": "",
                    "course_summary": "",
                    "base_color": "",
                    "app_icon_url": "",
                    "last_updated": null,
                    "registration_hidden": false,
                    "published_ios_version": "",
                    "published_android_version": "0"
                  }
                }
              ]
            }


## Sales [/courses/{courseId}/sales{?include,startDate,endDate,start,limit}]

### Create [POST /courses/{courseId}/sales]

You are only able to adjust the unit price and quantity of an item within a sale.  The taxes are generated automatically on the back-end and they default to include the tax in the price.

+ Request (application/json)

    + Attributes (Sales)
        
    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
    
    + Body
        
            {  
              "data":{  
                "type":"sales",
                "attributes":{
                  "employeeId":5478650,
                  "guestCount":0,
                  "number":485,
                  "terminalId":6,
                  "items":[  
                    {  
                      "type":"sales_items",
                      "attributes":{  
                        "itemId":5311,
                        "quantity":1,
                        "unitPrice":10,
                        "description":""
                      }
                    },
                    {  
                      "type":"sales_items",
                      "attributes":{  
                        "itemId":5311,
                        "quantity":1,
                        "unitPrice":10,
                        "description":""
                      }
                    }
                  ],
                  "payments":[  
                    {  
                      "type":"sales_payments",
                      "attributes":{  
                        "paymentAmount":20,
                        "invoiceId":"1",
                        "type":"credit_card"
                      }
                    }
                  ]
                }
              }
            }
        
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.


+ Response 200 (application/json)

            {
              "data": {
                "type": "sales",
                "id": "23464980",
                "attributes": {
                  "saleTime": {
                    "date": "2016-10-17 21:57:12.000000",
                    "timezone_type": 3,
                    "timezone": "UTC"
                  },
                  "comment": "",
                  "employeeId": 5478650,
                  "guestCount": 0,
                  "number": 9841,
                  "paymentType": "Credit Card: $21.00 - ",
                  "refundComment": "",
                  "refundReason": "",
                  "total": 21,
                  "subtotal": 21,
                  "tax": 0,
                  "deleted": false,
                  "deletedAt": null
                }
              }
            }

### List All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + limit: 10 (integer, optional)- Total results to show (Max: 100).
    + start: 0 (integer, optional)- Which result to start on.
    + startDate : `2016-07-06` (date,optional) - Must limit the sales returned to a single date.
    + endDate : `2016-07-08` (date,optional) - Must limit the sales returned to a single date.
    + include : items (enum[string],optional) - Which relationships to include in response. 
        + Members
            + `items`
+ Response 200 (application/json)

            {  
               "data":[  
                  {  
                     "type":"sales",
                     "id":"5191",
                     "attributes":{  
                        "saleTime":{  
                           "date":"2016-07-06 17:52:37.000000",
                           "timezone_type":3,
                           "timezone":"UTC"
                        },
                        "comment":"",
                        "employeeId":12,
                        "guestCount":0,
                        "number":485,
                        "paymentType":"Cash: $127.43<br />",
                        "refundComment":"",
                        "refundReason":"",
                        "total":127.43,
                        "subtotal":120,
                        "tax":7.43,
                        "deleted":false,
                        "deletedAt":null
                     },
                     "relationships":{  
                        "items":{  
                           "data":[  
                              {  
                                 "type":"sales_items",
                                 "id":"51911"
                              },
                              {  
                                 "type":"sales_items",
                                 "id":"51912"
                              }
                           ]
                        }
                     }
                  }
               ],
               "included":[  
                  {  
                     "type":"sales_items",
                     "id":"51911",
                     "attributes":{  
                        "total":"117.43",
                        "subTotal":"110.00",
                        "tax":"7.43",
                        "quantity":"1.00",
                        "unitPrice":"110.00",
                        "discountPercent":"0.00",
                        "profit":"110.00"
                     }
                  },
                  {  
                     "type":"sales_items",
                     "id":"51912",
                     "attributes":{  
                        "total":"10.00",
                        "subTotal":"10.00",
                        "tax":"0.00",
                        "quantity":"1.00",
                        "unitPrice":"10.00",
                        "discountPercent":"0.00",
                        "profit":"2.00",
                        "department":"Corporate",
                        "category":"clearance",
                        "subcategory":"hats",
                        "glCode":null,
                        "itemNumber":null,
                        "itemId": 5098,
                        "name": "Bermuda Sands Sweatshirt",
                        "description":"white/black"
                     }
                  }
               ]
            }

## Tee Sheets [/courses/{courseId}/teesheets]

### Get All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.

+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "teesheets",
                  "id": "26",
                  "attributes": {
                    "title": "Exec 9 holes",
                    "course_id": 6270
                  }
                },
                {
                  "type": "teesheets",
                  "id": "27",
                  "attributes": {
                    "title": "Main course 2",
                    "course_id": 6270
                  }
                },
                {
                  "type": "teesheets",
                  "id": "40",
                  "attributes": {
                    "title": "Putt putt",
                    "course_id": 6270
                  }
                },
                {
                  "type": "teesheets",
                  "id": "67",
                  "attributes": {
                    "title": "Jack Barnes",
                    "course_id": 6270
                  }
                },
                {
                  "type": "teesheets",
                  "id": "71",
                  "attributes": {
                    "title": "TESTER",
                    "course_id": 6270
                  }
                }
              ]
            }

## Terminals [/courses/{courseId}/terminals]

### Get All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.

+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "terminals",
                  "id": "6",
                  "attributes": {
                    "label": "Pro Shop"
                  }
                },
                {
                  "type": "terminals",
                  "id": "936",
                  "attributes": {
                    "label": "JH Terminal"
                  }
                }
              ]
            }           


## Employees [/courses/{courseId}/employees{?include,start,limit}]

### Get All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + limit: 10 (integer, optional)- Total results to show (Max: 100).
    + start: 0 (integer, optional)- Which result to start on.

+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "employees",
                  "id": "5478650",
                  "attributes": {
                    "user_level": 1,
                    "position": "",
                    "username": "tnash1",
                    "activated": 1,
                    "last_login": {
                      "date": "2016-10-17 04:25:41.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    },
                    "contact_info": {
                      "id": 5478650,
                      "first_name": "Trevor",
                      "last_name": "nash",
                      "phone_number": "",
                      "cell_phone_number": "",
                      "email": "fake@fake.com",
                      "birthday": null,
                      "address_1": "",
                      "address_2": "",
                      "city": "",
                      "state": "",
                      "zip": "",
                      "country": "",
                      "comments": ""
                    }
                  }
                }
              ]
            }

# Group Tee Sheets

## Bookings [/courses/{courseId}/teesheets/{teesheetId}/bookings{?include,startDate,endDate,start,limit}]

Bookings don't contain any pricing information and are purely the bookings on a teesheet.  
To get pricing information from a booking that's already been paid for you must include the sales relationship.  The sales object will include the customer information, payment details, and item details.

### Get All [GET]

###How should I distinguish green fees from other item?
Green fees and carts will have a category of "Green Fees" and "Carts" respectively.  The department can be customized but a course can't adjust the category.

###Is it possible to include players and sales.items at the same time ?
Yes, add this to your query: include=players,sales,sales.items

###How do you identify the booking type? (Customer, Member, Public, etc)
The sales_items object containes an attribute "PriceClass" that designates the green fee type.

+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + teesheetId : 1530 (integer) - A tee sheet id that the user has permission to access.
    + limit: 10 (integer, optional)- Total results to show (Max: 100).
    + start: 0 (integer, optional)- Which result to start on.
    + startDate : `2016-09-29` (date,optional) - Must limit the sales returned to a single date.
    + endDate : `2016-09-30` (date,optional) - Must limit the sales returned to a single date.
    + include : `players`,`sales` (enum[string],optional) - Which relationships to include in response. 
        + Members
            + `players`
            + `sales`
            + `sales.items`
            + `bookings`
            
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "bookings",
                  "id": "TTID_0117154814d25h0",
                  "attributes": {
                    "isReround": false,
                    "type": "teetime",
                    "status": "checked in",
                    "start": {
                      "date": "2016-09-29 13:26:00.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    },
                    "end": {
                      "date": "2016-09-29 13:34:00.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    },
                    "duration": 0,
                    "playerCount": 2,
                    "holes": 1,
                    "carts": 0,
                    "paidPlayerCount": 2,
                    "noShowCount": 0,
                    "title": "Hopkins",
                    "details": "Reserved using online booking @ 2:53pm 1/16 MST",
                    "side": "front",
                    "bookingSource": "online",
                    "lastUpdated": {
                      "date": "2016-09-29 21:33:01.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    },
                    "dateBooked": {
                      "date": "2013-01-17 23:48:14.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    },
                    "dateCancelled": null,
                    "turnTime": null,
                    "finishTime": null
                  },
                  "relationships": {
                    "players": {
                      "data": [
                        {
                          "type": "people",
                          "id": "30"
                        }
                      ]
                    }
                  }
                }
              ],
              "included": [
                {
                  "type": "people",
                  "id": "30",
                  "attributes": {
                    "first_name": "Zipadee",
                    "last_name": "Hopkins",
                    "phone_number": "",
                    "cell_phone_number": "",
                    "email": "brendon.beebe@gmail.com",
                    "birthday": null,
                    "address_1": "",
                    "address_2": "",
                    "city": "",
                    "state": "",
                    "zip": "",
                    "country": "",
                    "comments": ""
                  }
                }
              ]
            }

## Stats [/courses/{courseId}/teesheets/{teesheetId}/stats{?date}]

### Get All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzg5MDQxMDIsImV4cCI6MTUxMDAwODEwMiwibGV2ZWwiOjMsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6MTYzNywiZW1wSWQiOjE2MzcsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.ooY5m1n3qurbJhkRzrviVPVailuKnLXbImHO8-y-p9ryejEpeE-IUrS_APJpAQcGTxY7YCQL_qhRgRbeSriW8A
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + teesheetId : 1562 (integer) - A tee sheet id that the user has permission to access.
    + date : `2016-05-19` (date) - Must limit the stats returned to a single date.
            
+ Response 200 (application/json)

            {
              "data": {
                "type": "teesheet_stats",
                "id": "2016-09-28",
                "attributes": {
                  "bookings": "1",
                  "occupancy": "0%",
                  "playerNoShows": "1",
                  "playersCheckedIn": 0,
                  "revenue": "$486.30"
                }
              }
            }

# Group Customers

## Customer Collection [/courses/{courseId}/customers{?limit,start}]

### List All [GET]

+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + start : 0 (integer,optional) - Which result to start on.
    + limit : 10 (integer,optional) - Total results to show.
    
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "customers",
                  "id": "2073",
                  "attributes": {
                    "username": "username",
                    "account_number": "123ABC",
                    "company_name": "MyCompany",
                    "taxable": true,
                    "discount": 0,
                    "opt_out_email": false,
                    "opt_out_text": false,
                    "date_created": null,
                    "contact_info": {
                      "id": 2073,
                      "first_name": "FirstName",
                      "last_name": "LastName",
                      "phone_number": "",
                      "cell_phone_number": "",
                      "email": "foreup@fake.com",
                      "birthday": null,
                      "address_1": "",
                      "address_2": "",
                      "city": "",
                      "state": "AL",
                      "zip": "",
                      "country": "",
                      "comments": "Best customer ever!!"
                    }
                  }
                }
              ]
            }
            
## Specific Customer [/courses/{courseId}/customers/{customerId}{?include,limit,start}]

### Get One [GET]

+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters

    + courseId : 9039 - A course id that the user has permission to access.
    + customerId : 3612897 - The customer id.
    + start : 0 (integer,optional) - Which result to start on.
    + limit : 10 (integer,optional) - Total results to show.
    + include : sales (enum[string],optional) - Which relationships to include in response. 
        + Members
            + `sales`
            + `sales.items`
                
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "customers",
                  "id": "2073",
                  "attributes": {
                    "username": "username",
                    "account_number": "123ABC",
                    "company_name": "MyCompany",
                    "taxable": true,
                    "discount": 0,
                    "opt_out_email": false,
                    "opt_out_text": false,
                    "date_created": null,
                    "contact_info": {
                      "id": 2073,
                      "first_name": "FirstName",
                      "last_name": "LastName",
                      "phone_number": "",
                      "cell_phone_number": "",
                      "email": "foreup@fake.com",
                      "birthday": null,
                      "address_1": "",
                      "address_2": "",
                      "city": "",
                      "state": "AL",
                      "zip": "",
                      "country": "",
                      "comments": "Best customer ever!!"
                    }
                  }
                }
              ]
            }
            
## Customer Sales [/courses/{courseId}/customers/{customerId}/sales{?include,limit,start}]

### List All [GET]

+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + customerId : 3612897 - The customer id.
    + limit: 10 (integer,optional) - Total results to show (Max: 100).
    + start: 0 (integer,optional) - Which result to start on.
    + include : items (enum[string],optional) - Which relationships to include in response. 
        + Members
            + `items`
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "sales",
                  "id": "5052",
                  "attributes": {
                    "saleTime": {
                      "date": "2016-08-26 16:39:01.000000",
                      "timezone_type": 3,
                      "timezone": "UTC"
                    },
                    "comment": "",
                    "employeeId": 185,
                    "guestCount": 0,
                    "number": 346,
                    "paymentType": "Cash: $11.88<br />",
                    "refundComment": "",
                    "refundReason": "",
                    "total": 10,
                    "subtotal": 10,
                    "tax": 0,
                    "deleted": false,
                    "deletedAt": null
                  },
                  "relationships": {
                    "items": {
                      "data": [
                        {
                          "type": "sales_items",
                          "id": "50521"
                        }
                      ]
                    }
                  }
                }
              ],
              "included": [
                {
                  "type": "sales_items",
                  "id": "50521",
                  "attributes": {
                    "total": 10,
                    "subTotal": 10,
                    "tax": 0,
                    "quantity": 1,
                    "unitPrice": 10,
                    "discountPercent": 0,
                    "profit": 8,
                    "department": "Pro Shop",
                    "category": "Equipment",
                    "subcategory": "Golf Balls",
                    "glCode": null,
                    "itemNumber": null,
                    "description": "Quality Golf Balls"
                  }
                }
              ]
            }
                   
# Group Inventory
## Item Collection [/courses/{courseId}/items{?limit,start}]

Inventory Items consist of Item Kits, Items, Service Fees, Passes, and Punch Cards.  This does not include tee times which are handled separately.

### List All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + limit: 10 (integer,optional) - Total results to show (Max: 100).
    + start: 0 (integer,optional)- Which result to start on.
    
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "items",
                  "id": "383",
                  "attributes": {
                    "maxDiscount": 100,
                    "addOnPrice": 0,
                    "costPrice": 0,
                    "courseId": 6270,
                    "quantity": 1000,
                    "numberOfSides": 0,
                    "unitPrice": 10000000,
                    "category": "Services",
                    "itemNumber": null,
                    "location": "",
                    "name": "Joel Ragar",
                    "subcategory": "",
                    "department": "Food & Beverage",
                    "description": "",
                    "glCode": null,
                    "usInactive": false,
                    "doNotPrint": false,
                    "deleted": true,
                    "isfoodAndBeverage": false,
                    "isInvisible": false,
                    "isFree": false,
                    "isGiftcard": false,
                    "isPass": false,
                    "isSide": false,
                    "isUnlimited": false,
                    "isSoupOrSalad": true,
                    "unitPriceIncludesTAx": false
                  }
                }
              ]
            }
            

## Transaction Collection [/courses/{courseId}/inventory{?include,startDate,endDate,limit,start}]

    This is a record of each adjustment made to a courses inventory.  A negative number signifies one less item is available while a positive number means an item was added.

### List All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
        
+ Parameters
    + courseId : 9039 - A course id that the user has permission to access.
    + limit: 10 (Integer, optional)- Total results to show (Max: 100).
    + start: 0 (Integer, optional)- Which result to start on.
    + startDate : `2016-05-19` (date,optional) - Must limit the sales returned to a single date.
    + endDate : `2016-05-19` (date,optional) - Must limit the sales returned to a single date.
    + include : items (enum[string],optional) - Which relationships to include in the response. 
        + Members
            + `employees`
            + `sales`
            + `items`
+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "inventory",
                  "id": "8810",
                  "attributes": {
                    "comment": "Manual Edit of Quantity",
                    "adjustmentAmount": -1,
                    "courseId": 6270,
                    "itemId": 5286,
                    "itemNumber": 0,
                    "transDate": {
                      "date": "2016-09-01 11:31:29.000000",
                      "timezone_type": 3,
                      "timezone": "America/Denver"
                    }
                  }
                }
              ]
            }

# Group Webhook

A webhook allows you to recieve instanst feedback when ever something happens on the foreUp system.  See a list of the available events [below](#reference/webhook-events/delete).

We recommend using [Request Bin](https://requestb.in/) to play with the hooks.  It will record all calls from our system to the hook and help you understand how the calls are made.

## Hooks Collection [/hooks]

### List All [GET]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag

+ Response 200 (application/json)

            {
              "data": [
                {
                  "type": "api_hooks",
                  "id": "3",
                  "attributes": {
                    "url": "http://google.com",
                    "event": "customer.updated"
                  }
                }
              ]
            }


### Create [POST]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag
    
    + Body
        
            {  
              "data":{  
                "type":"api_hooks",
                "attributes":{  
                    "url":"http://google.com",
                    "event":"customer.updated"
                }
              }
            }

+ Response 200 (application/json)

            {
              "data": {
                "type": "api_hooks",
                "id": "4",
                "attributes": {
                  "url": "http://google.com",
                  "event": "customer.updated"
                }
              }
            }
            
### Delete [DELETE /hooks/{id}]
+ Request (application/json)

    + Headers
    
            x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag

+ Response 200 (application/json)

            {
              "success": true
            }


# Group Webhook Events 

    foreUp’s Event Webhook will notify a URL of your choice via HTTP POST with information about events that occur in a course.
        These events include:
    
## Customer Updated (Event key: customer.updated)

This event triggers when a customer is edited

* From within the customer module
* From the tee sheet
* From logging into online booking and editing their own information

        {
            "event":"customer.updated",
            "course_id":"6270",
            "id":"342234432"
        }

## Tee Time Updated (Event key: teetime.updated)

The only way to know how a tee time has changed is by issueing a seperate call to our servers to get information on the tee time.  We recommend refreshing your local information about a tee time every time this calls comes through.

This event triggers when:

* An employee clicks the update button in the tee sheet
* The tee time is moved from within the tee sheet

        {
            "event":"teetime.updated",
            "course_id":"6270",
            "id":"342234432"
        }
        
## Tee Time Deleted (Event key: teetime.deleted)

This triggers when:

* A customer cancels the tee time from online booking
* An employee deletes the time

        {
            "event":"teetime.deleted",
            "course_id":"6270",
            "id":"342234432"
        }
        
## Sale Created (Event key: sale.created)

Sales may or may not have a customer attached.  This event triggers any time a sale is complete through the POS.

        {
            "event":"sale.created",
            "course_id":"6270",
            "id":"342234432"
        }
        
# Data Structures

## Headers (object)
+ x-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE0Nzc1OTUzOTYsImV4cCI6MTUwODY5OTM5NiwibGV2ZWwiOjEsImNpZCI6OTAzOSwiZW1wbG95ZWUiOnRydWUsInVpZCI6NTQ3ODY1MCwiZW1wSWQiOjU0Nzg2NTAsImFwcElkIjo2NDgyNzI4LCJwcmljZUNsYXNzSWQiOm51bGx9.lHiBf6aoIEbhDTBATMUrnO7oJIqsIm13Zl7zyIQoYKxeF0WBbL0oxk2AWxSy13hOQJVjI4pOMgT0p5u1majTag


## Sales (object)
+ employeeId:  "5478650" (string,required) - The id of the employee completing the sale
+ guestCount:  3 (number,optional) - Number of guests on the sale.  Used in reporting.
+ number:  485 (number,required) - The customer facing sale number. Used on reciepts
+ terminalid: 6 (number,required) - The id of the terminal this sale will be recorded under.
+ items (array)
    + (Sales Items)
+ payments (array)
    + (Payments)

## Sales Items
+ itemId:  5311 (number,required) - A valid item id currently found in the courses inventory.
+ quantity:  1 (number,required) - Total items purchased.
+ unitPrice:  10 (number,required) - Price per individual item sold with tax
+ description:  Cool Item (string,optional) - Optional message to save with the item.

## Payments
+ paymentAmount:  20 (number,required) - Total amount paid for by this payment type.
+ invoiceId:  1 (number,required) - A unique identifier the course can link back to their payment processor.
+ type : credit_card (enum[string],required) - Identifier showing how the payment was processed
    + Members
        + `credit_card`
        + `cash`
        + `change`
        + `member_account`
        + `gift_card`
        + `punch_card`